apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: healthcare-ai-kyverno-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/testoranit/healthcare-ai-platform-gitops.git
    targetRevision: main
    path: platform/kyverno-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
