apiVersion: v1
kind: Namespace
metadata:
  name: healthcare-ai-prod
  labels:
    environment: prod
    app.kubernetes.io/part-of: healthcare-ai-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
