apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: healthcare-ai-stage

resources:
  - ../../base

images:
  - name: healthcare-ai-agent
    newName: 021655150740.dkr.ecr.ap-south-1.amazonaws.com/healthcare-ai-dev-agent
    newTag: initial
